







; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32@6.3.2
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs

build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE    # Use angle brackets for lv_conf.h
    -D LV_CONF_PATH=lv_conf.h    # Specify the config file name
    -D CORE_DEBUG_LEVEL=0         # Disable debug output
    -Os                           # Optimize for size
lib_deps =
    lvgl/lvgl@^8.3.1
    256dpi/MQTT@^2.5.2
    Bodmer/TFT_eSPI@^2.4.0
    bitbank2/PNGdec
    Bodmer/TJpg_Decoder
    64 
    https://github.com/Links2004/arduinoWebSockets.git#2.7.1
    256dpi/MQTT@^2.5.2
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
    adafruit/Adafruit PN532 @ ^1.2.0
    
    